#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"ConfigMap", "metadata":{"name":"config-observability"}})
---
#@overlay/match-child-defaults missing_ok=True
data: #@ data.values.config["observability"]
