#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#! On AKS, we disable the Admissions Enforcer so that it doesn't interfer with the Knative Serving webhooks.
#! See: https://github.com/knative/pkg/issues/1590
#! See: https://github.com/knative/serving/issues/12474
#! See: https://learn.microsoft.com/en-us/azure/aks/faq#can-admission-controller-webhooks-impact-kube-system-and-internal-aks-namespaces

#@ mutating_webhook = overlay.subset({"apiVersion": "admissionregistration.k8s.io/v1", "kind": "MutatingWebhookConfiguration"})
#@ validating_webhook = overlay.subset({"apiVersion": "admissionregistration.k8s.io/v1", "kind": "ValidatingWebhookConfiguration"})

#@overlay/match by=overlay.or_op(mutating_webhook,validating_webhook), expects="6+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    admissions.enforcer/disabled: "true"
